# Generated by Django 5.1.2 on 2024-11-05 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_remove_recipe_image_recipe_featured'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='calories',
            field=models.PositiveIntegerField(help_text='Total calories in kcal'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='preparation_time',
            field=models.DurationField(help_text='Preparation time in hours, minutes, and seconds (hh:mm:ss)'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='servings',
            field=models.PositiveIntegerField(help_text='Number of servings'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='total_time',
            field=models.DurationField(help_text='Total cooking time in hours, minutes, and seconds (hh:mm:ss)'),
        ),
    ]
